### ISSUE TITLE
crash when player jumped a ship into sync range

### ISSUE THREAD

**Issue by Allen-Wrench** [Casimir255/SeamlessClientPlugin#5]
```xml
2021-03-31 01:40:56.700 - Thread:   1 ->  Exception occurred: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Sandbox.Game.GameSystems.CoordinateSystem.MyCoordinateSystem.CreateCoordSys_ClientInternal(MyTransformD& transform, Int64 coordSysId)
   at Sandbox.Game.GameSystems.CoordinateSystem.MyCoordinateSystem.CoordSysCreated_Client<>Sandbox_Game_GameSystems_CoordinateSystem_MyCoordinateSystem<>MyCreateCoordSysBuffer.Invoke(IMyEventOwner& <static>, MyCreateCoordSysBuffer& createBuffer, DBNull& arg2, DBNull& arg3, DBNull& arg4, DBNull& arg5, DBNull& arg6)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationClient.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationClient.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
2021-03-31 01:40:56.701 - Thread:   1 ->  Packet processing error, disconnecting VRage.Network.Endpoint
2021-03-31 01:40:56.707 - Thread:   1 ->  Exception occurred: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Sandbox.Game.GameSystems.CoordinateSystem.MyCoordinateSystem.CreateCoordSys_ClientInternal(MyTransformD& transform, Int64 coordSysId)
   at Sandbox.Game.GameSystems.CoordinateSystem.MyCoordinateSystem.CoordSysCreated_Client<>Sandbox_Game_GameSystems_CoordinateSystem_MyCoordinateSystem<>MyCreateCoordSysBuffer.Invoke(IMyEventOwner& <static>, MyCreateCoordSysBuffer& createBuffer, DBNull& arg2, DBNull& arg3, DBNull& arg4, DBNull& arg5, DBNull& arg6)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationClient.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationClient.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
   at Sandbox.Engine.Networking.MyNetworkReader.Process()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   ```

**Comment by Casimir255** [comment]
Related to issue #2

**Comment by Casimir255** [comment]
Once that is fixed, should also fix this error

**Comment by Casimir255** [comment]
Fixed in latest release
